CREATE USER IF NOT EXISTS SA SALT 'f60d69595a95f7e1' HASH 'ce02e1a1202ac25865755e622d5ba60adf1428d3c58d2864f3119803dab34d1f' ADMIN;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8B9A2016_E628_4526_9DE5_B9A572D64DDF START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C04B39B1_C979_4B2C_9381_4EF8A009C466 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EFD0AFB8_AAD1_4904_B096_11CC34624B28 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2EEB4254_254B_4CE5_82EC_5D561A0D7CD2 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F920CC64_4A40_4BFE_AEAE_332DAD6E54BA START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CCCC981B_5661_45C3_9456_5C0565F55057 START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE PUBLIC.CATALOG(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CCCC981B_5661_45C3_9456_5C0565F55057) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CCCC981B_5661_45C3_9456_5C0565F55057,
    NAME VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.CATALOG ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CATALOG;
CREATE CACHED TABLE PUBLIC.DESCRIPTION(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8B9A2016_E628_4526_9DE5_B9A572D64DDF) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8B9A2016_E628_4526_9DE5_B9A572D64DDF,
    VALUE BIGINT NOT NULL
);
ALTER TABLE PUBLIC.DESCRIPTION ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DESCRIPTION;
CREATE CACHED TABLE PUBLIC.DESCRIPTIONS(
    ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(255),
    DESCRIPTION_ORDER INTEGER NOT NULL
);
ALTER TABLE PUBLIC.DESCRIPTIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_17 PRIMARY KEY(ID, DESCRIPTION_ORDER);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DESCRIPTIONS;
CREATE CACHED TABLE PUBLIC.ITEM(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_EFD0AFB8_AAD1_4904_B096_11CC34624B28) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EFD0AFB8_AAD1_4904_B096_11CC34624B28,
    NAME VARCHAR(255) NOT NULL,
    TYPE INTEGER NOT NULL,
    IMAGE BIGINT NOT NULL
);
ALTER TABLE PUBLIC.ITEM ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ITEM;
CREATE CACHED TABLE PUBLIC.ITEM_DESCRIPTION(
    ITEM BIGINT NOT NULL,
    DESCRIPTION BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ITEM_DESCRIPTION;
CREATE CACHED TABLE PUBLIC.SECTION(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_C04B39B1_C979_4B2C_9381_4EF8A009C466) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C04B39B1_C979_4B2C_9381_4EF8A009C466,
    NAME VARCHAR(255) NOT NULL,
    TYPE INTEGER NOT NULL,
    CATALOG BIGINT,
    IMAGE BIGINT NOT NULL
);
ALTER TABLE PUBLIC.SECTION ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SECTION;
CREATE CACHED TABLE PUBLIC.SECTION_DESCRIPTION(
    SECTION BIGINT NOT NULL,
    DESCRIPTION BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SECTION_DESCRIPTION;
CREATE CACHED TABLE PUBLIC.SECTION_ITEMS(
    SECTION BIGINT NOT NULL,
    ITEMS BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SECTION_ITEMS;
CREATE CACHED TABLE PUBLIC.SECTION_SUB_SECTIONS(
    SECTION BIGINT NOT NULL,
    SUB_SECTIONS BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SECTION_SUB_SECTIONS;
CREATE CACHED TABLE PUBLIC.THUMBNAIL(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_2EEB4254_254B_4CE5_82EC_5D561A0D7CD2) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2EEB4254_254B_4CE5_82EC_5D561A0D7CD2,
    IMAGE BLOB NOT NULL,
    PATH VARCHAR(255) NOT NULL,
    TYPE INTEGER NOT NULL
);
ALTER TABLE PUBLIC.THUMBNAIL ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.THUMBNAIL;
CREATE CACHED TABLE PUBLIC.VALUE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F920CC64_4A40_4BFE_AEAE_332DAD6E54BA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F920CC64_4A40_4BFE_AEAE_332DAD6E54BA,
    SR_KEY VARCHAR(255) NOT NULL,
    CATALOG BIGINT NOT NULL
);
ALTER TABLE PUBLIC.VALUE ADD CONSTRAINT PUBLIC.CONSTRAINT_4D PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VALUE;
ALTER TABLE PUBLIC.SECTION_SUB_SECTIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_29 UNIQUE(SUB_SECTIONS);
ALTER TABLE PUBLIC.VALUE ADD CONSTRAINT PUBLIC.CONSTRAINT_4DA UNIQUE(SR_KEY, CATALOG);
ALTER TABLE PUBLIC.SECTION_DESCRIPTION ADD CONSTRAINT PUBLIC.CONSTRAINT_B UNIQUE(DESCRIPTION);
ALTER TABLE PUBLIC.ITEM_DESCRIPTION ADD CONSTRAINT PUBLIC.CONSTRAINT_6 UNIQUE(DESCRIPTION);
ALTER TABLE PUBLIC.SECTION_ITEMS ADD CONSTRAINT PUBLIC.FKB16649E6C4B2D1A FOREIGN KEY(SECTION) REFERENCES PUBLIC.SECTION(ID) NOCHECK;
ALTER TABLE PUBLIC.SECTION_SUB_SECTIONS ADD CONSTRAINT PUBLIC.FK1187E067C4B2D1A FOREIGN KEY(SECTION) REFERENCES PUBLIC.SECTION(ID) NOCHECK;
ALTER TABLE PUBLIC.SECTION_DESCRIPTION ADD CONSTRAINT PUBLIC.FK137931A2C4B2D1A FOREIGN KEY(SECTION) REFERENCES PUBLIC.SECTION(ID) NOCHECK;
ALTER TABLE PUBLIC.SECTION ADD CONSTRAINT PUBLIC.FK756F7EE563AAEF82 FOREIGN KEY(CATALOG) REFERENCES PUBLIC.CATALOG(ID) NOCHECK;
ALTER TABLE PUBLIC.DESCRIPTION ADD CONSTRAINT PUBLIC.FK993583FC83A8E632 FOREIGN KEY(VALUE) REFERENCES PUBLIC.VALUE(ID) NOCHECK;
ALTER TABLE PUBLIC.SECTION_SUB_SECTIONS ADD CONSTRAINT PUBLIC.FK1187E067DA318782 FOREIGN KEY(SUB_SECTIONS) REFERENCES PUBLIC.SECTION(ID) NOCHECK;
ALTER TABLE PUBLIC.SECTION_ITEMS ADD CONSTRAINT PUBLIC.FKB16649E6D031F583 FOREIGN KEY(ITEMS) REFERENCES PUBLIC.ITEM(ID) NOCHECK;
ALTER TABLE PUBLIC.VALUE ADD CONSTRAINT PUBLIC.FK6AC917163AAEF82 FOREIGN KEY(CATALOG) REFERENCES PUBLIC.CATALOG(ID) NOCHECK;
ALTER TABLE PUBLIC.SECTION ADD CONSTRAINT PUBLIC.FK756F7EE5CC669597 FOREIGN KEY(IMAGE) REFERENCES PUBLIC.THUMBNAIL(ID) NOCHECK;
ALTER TABLE PUBLIC.SECTION_DESCRIPTION ADD CONSTRAINT PUBLIC.FK137931A2588F0F48 FOREIGN KEY(DESCRIPTION) REFERENCES PUBLIC.DESCRIPTION(ID) NOCHECK;
ALTER TABLE PUBLIC.DESCRIPTIONS ADD CONSTRAINT PUBLIC.FK8D7AFBF7BF599867 FOREIGN KEY(ID) REFERENCES PUBLIC.DESCRIPTION(ID) NOCHECK;
ALTER TABLE PUBLIC.ITEM_DESCRIPTION ADD CONSTRAINT PUBLIC.FK5AAC58D0CA6588D6 FOREIGN KEY(ITEM) REFERENCES PUBLIC.ITEM(ID) NOCHECK;
ALTER TABLE PUBLIC.ITEM_DESCRIPTION ADD CONSTRAINT PUBLIC.FK5AAC58D0588F0F48 FOREIGN KEY(DESCRIPTION) REFERENCES PUBLIC.DESCRIPTION(ID) NOCHECK;
ALTER TABLE PUBLIC.ITEM ADD CONSTRAINT PUBLIC.FK317B13CC669597 FOREIGN KEY(IMAGE) REFERENCES PUBLIC.THUMBNAIL(ID) NOCHECK;
